backend:
  name: github
  repo: codebluesolutionsllc/website-option2   # your GitHub repo
  branch: main
  auth_type: oauth
  client_id: Ov23liBEGDX9ATyCt5Cn   # from GitHub OAuth app
  base_url: https://codebluesolutionsllc.github.io/website-option2

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "body", label: "Body", widget: "markdown" }
